#!/bin/bash

echo "=== Verificando configuración del destination shiftbook-backend ==="
echo ""
echo "El destination debe tener estas propiedades para OAuth2UserTokenExchange:"
echo ""
echo "Authentication: OAuth2UserTokenExchange"
echo "tokenServiceURLType: Dedicated"
echo "tokenServiceURL: https://gbi-manu-dev.authentication.us10.hana.ondemand.com/oauth/token"
echo "clientId: sb-shiftbook-srv-manu-dev-org-dev-v3!t459223"
echo "clientSecret: 2bd17d2f-7f40-47f8-ad57-d100643f6ba3\$--------------CEo5EGza5aYORcjI_ReEG_g9k2CFAU2cc="
echo ""
echo "=== Verificación Manual Requerida ==="
echo "1. Ve a BTP Cockpit → Connectivity → Destinations"
echo "2. Busca 'shiftbook-backend'"
echo "3. Verifica que tenga estas propiedades exactas"
echo "4. Si no las tiene, edítalo y actualiza"
echo ""
echo "⚠️  IMPORTANTE: El clientId y clientSecret deben ser del servicio XSUAA"
echo "   del backend (shiftbook-srv), NO del destination service"
